services:
  starrupture:
    image: rhavinx/starrupture:latest
    #image: ghcr.io/rhavinx/starrupture:latest # Alternate location
    container_name: starrupture
    environment:
      TZ: "UTC"
      SKIP_UPDATE: "0"
      ENABLE_LOG: "1"
      GAME_PORT: "7777"
      # ADMIN_PASSWORD: ""
      # PLAYER_PASSWORD: ""
      # FORCE_CHANGE_ADMIN: "0"
      # FORCE_CHANGE_PLAYER: "0"
      # REMOVE_SERVER_FILES: "0"
      # BACKUP_SETTINGS: "1"
    volumes: # Internal Volume Paths have changed. Removed saves mount.
      - /path/to/server:/home/steam/starrupture/server
      - /path/to/data:/home/steam/starrupture/data
    ports:
      - "7777:7777/udp"
      # - "7777:7777/tcp"  # Removed to mitigate vulnerability.
    restart: unless-stopped